---
- name: clear tlsauth
  file:
    path: "{{tls_auth_path}}"
    state: absent
  when: clear_all or clear_tlsauth

- name: check tlsauth existence
  stat:
    path: "{{tls_auth_path}}"
  register: tls_auth_certificate

- name: build tls_auth key
  raw: openvpn --genkey --secret {{tls_auth_path}}
  when: tls_auth_certificate.stat.exists is defined and not tls_auth_certificate.stat.exists
  notify:
    - uci commit openvpn
    - restart openvpn
