---
- name: build ca in non-interactive mode
  lineinfile:
    line: '"/usr/sbin/pkitool" --initca $*'
    regexp: '^"/usr/sbin/pkitool"( --interact)? --initca \$\*$'
    dest: /usr/sbin/build-ca

- name: build server certificate request in non-interactive mode
  lineinfile:
    line: '"/usr/sbin/pkitool" --server $*'
    regexp: '^"/usr/sbin/pkitool"( --interact)? --server \$\*$'
    dest: /usr/sbin/build-key-server

- name: build client certificate in non-interactive mode
  lineinfile:
    line: '"/usr/sbin/pkitool" $*'
    regexp: '^"/usr/sbin/pkitool"( --interact)? \$\*$'
    dest: /usr/sbin/build-key
